!classDefinition: #Bill category: #Ejercicio1!
DenotativeObject subclass: #Bill
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Bill class' category: #Ejercicio1!
Bill class
	instanceVariableNames: 'energia'!


!classDefinition: #Bill2 category: #Ejercicio1!
Object subclass: #Bill2
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio1'!
